import { copyFile, mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

const packageDirectory = path.resolve("node_modules/@fontsource/noto-sans");
const regular = await readFile(path.join(packageDirectory, "files/noto-sans-latin-400-normal.woff2"));
const bold = await readFile(path.join(packageDirectory, "files/noto-sans-latin-700-normal.woff2"));
const targetDirectory = path.resolve("themes/modern-europass/assets/fonts");
await mkdir(targetDirectory, { recursive: true });
await copyFile(path.join(packageDirectory, "LICENSE"), path.join(targetDirectory, "OFL-1.1.txt"));
await writeFile(
  path.resolve("themes/modern-europass/fonts.ts"),
  `// Generated by scripts/embed-fonts.ts from @fontsource/noto-sans.\nexport const notoSansRegular = ${JSON.stringify(regular.toString("base64"))};\nexport const notoSansBold = ${JSON.stringify(bold.toString("base64"))};\n`,
  "utf8",
);
console.log("Embedded Noto Sans regular and bold weights.");
